spring:
  application:
    name: hhplus
  profiles:
    active: local
  datasource:
    name: ECommerceDataSource
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 3
      connection-timeout: 10000
      max-lifetime: 60000
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.timezone.default_storage: NORMALIZE_UTC
      hibernate.jdbc.time_zone: UTC

---
spring.config.activate.on-profile: local

spring:
  datasource:
    url: jdbc:mysql://localhost:3406/e_commerce_db?characterEncoding=UTF-8&serverTimezone=UTC
    username: application
    password: application
  data:
    redis:
      host: localhost
      port: 6479
      timeout: 2000ms
      connect-timeout: 2000ms

# Redisson 설정
spring.redis.redisson.config:
  singleServerConfig:
    address: "redis://localhost:6479"
    connectionMinimumIdleSize: 5
    connectionPoolSize: 10
    database: 0
    idleConnectionTimeout: 10000
    connectTimeout: 2000
    timeout: 2000
    retryAttempts: 2
    retryInterval: 1500

logging:
    level:
        com.example.demo1.DemoService: debug
